/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.biblioteca;

import br.com.biblioteca.boundary.PrincipalBoundary;
import javafx.application.Application;

public class App {
    public String getGreeting() {
        return "Biblioteca em execução!";
    }

    public static void main(String[] args) {
        new App().getGreeting();
        Application.launch(PrincipalBoundary.class, args);
    }
}
